[project]
name = 'LegalDoc-Chain'
description = ''
authors = []
telemetry = true
cache_dir = '.\.cache'
requirements = []
[contracts.LegalDoc-Chain]
path = 'contracts/LegalDoc-Chain.clar'
clarity_version = 3
epoch = 3.1

[contracts.ComplianceVerification]
path = 'contracts/ComplianceVerification.clar'
clarity_version = 3
epoch = 3.1

[contracts.LegalDoc-Templates]
path = 'contracts/LegalDoc-Templates.clar'
clarity_version = 3
epoch = 3.1

[contracts.book-reco-engine]
path = 'contracts/book-reco-engine.clar'
clarity_version = 3
epoch = 3.1

[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
